version: '3.8'

services:
  quickbite-user:
    image: quickbite-user-service:latest
    container_name: quickbite-user
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres_db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=user_db
    networks:
      - quickbite-net

  quickbite-restaurant:
    image: quickbite-restaurant-service:latest
    container_name: quickbite-restaurant
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres_db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=restaurant_db
    networks:
      - quickbite-net

  quickbite-order:
    image: quickbite-order-service:latest
    container_name: quickbite-order
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres_db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=order_db
    networks:
      - quickbite-net

  quickbite-notification:
    image: quickbite-notification-service:latest
    container_name: quickbite-notification
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=postgres_db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=notification_db
    networks:
      - quickbite-net

# Khai báo mạng ngoài (external network)
networks:
  quickbite-net:
    external: true